### ISSUE TITLE
Return to previous place when using the "/spec playerName" command again

### ISSUE THREAD

**Issue by Zzeyy** [LeoMeinel/SpecPlayer#6]
**Describe the feature**
So basically a lot of players just want to skip typing commands when they can just press the up arrow key.
But running the command to spectate a player again won't return the spectator to their previous place.

**Comment by Zzeyy** [comment]
Also I like this plugin, works as intended, doesn't even need any configuration. I give this plugin 5 stars on Spigot page.

**Comment by LeoMeinel** [comment]
> **Describe the feature** So basically a lot of players just want to skip typing commands when they can just press the up arrow key. But running the command to spectate a player again won't return the spectator to their previous place.

I'll try to implement this in the coming days! Seems like a good idea, I honestly didn't even think of that but it seems easy to implement, thanks for the suggestion :+1:

**Comment by LeoMeinel** [comment]
The new release should fix your issue!

**Comment by Zzeyy** [comment]
Thanks a lot, man
